/** Early pipeline statuses — full list in THP-SMB-ENGAGEMENT-001 §4 */
export const LIFECYCLE_STATUSES = [
  'application_submitted',
  'application_under_review',
  'qualification_invited',
  'qualification_active',
  'conditionally_qualified',
  'qualified',
  'too_early',
  'outside_current_scope',
  'not_ready_for_thp',
  'diagnostic_preparation',
  'diagnostic_active',
  'findings_ready',
  'findings_presented',
  'engagement_proposed',
  'agreement_pending',
  'payment_pending',
  'intervention_ready',
  'intervention_active',
  'intervention_paused',
  'referred',
  'reassessment_active',
  'completed_level_2',
  'completed_partial',
  'terminated',
  'withdrawn',
] as const

export const QUALIFICATION_RESULTS = [
  'qualified',
  'conditionally_qualified',
  'too_early',
  'outside_current_scope',
  'not_ready_for_thp',
] as const

export type LifecycleStatus = (typeof LIFECYCLE_STATUSES)[number]
export type QualificationResult = (typeof QUALIFICATION_RESULTS)[number]

export const applicationSelect = {
  id: true,
  submittedAt: true,
  form: true,
  version: true,
  founderName: true,
  businessName: true,
  email: true,
  contactPhone: true,
  coreOffer: true,
  payingCustomers: true,
  deliveryHistory: true,
  operatingStatus: true,
  founderContinuation: true,
  onlineActivity: true,
  primaryProblems: true,
  availableRecords: true,
  discoverySource: true,
  willingnessExamine: true,
  willingnessEvidence: true,
  willingnessFeedback: true,
  crisisIndicators: true,
  privacyAck: true,
  clientId: true,
  lifecycleStatus: true,
  qualificationResult: true,
  maturityClassification: true,
  assignedReviewer: true,
  missingEvidence: true,
  nextAction: true,
  paymentStatus: true,
  activeCapacitySlot: true,
  notes: true,
  createdAt: true,
  updatedAt: true,
} as const
